# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('publish_time', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('content', models.TextField(verbose_name='正文')),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-id'],
            },
        ),
    ]
