# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blog', '0003_auto_20170224_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last edited'),
        ),
    ]
