# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blog', '0004_article_last_edit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='last_edit_date',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
