# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blog', '0006_auto_20170224_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
