# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blog', '0008_auto_20170302_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('body', models.TextField(verbose_name='正文')),
                ('pub_date', models.DateField(verbose_name='发表日期')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
