# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blog', '0009_auto_20170302_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
