# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blog', '0011_blogpost_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
    ]
