# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blog', '0013_auto_20170315_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('acg', 'Anime & Manga & Novel & Game'), ('nc', 'No Category')], max_length=30, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]
